cs2610/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^aboot$', views.aboot, name='aboot'),
    url(r'^tech$', views.tech, name='tech'),
    url(r'^archive$', views.archive, name='archive'),
    url(r'^(?P<blog_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<blog_id>[0-9]+)/comment/$', views.comment, name='comment'),
]

cs2610/cs2610/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^convertAPI/', include('goldapi.urls')),
    url(r'^gold/', include('gold.urls')),
]

cs2610/gold/urls.py
from django.conf.urls import url
from . import views

app_name = "gold"
urlpatterns = [
        url(r'^$',views.goldWeight, name='gold'),
]

cs2610/goldapi/urls.py
from django.conf.urls import url
from . import views

app_name = "goldapi"
urlpatterns = [
        url(r'^$',views.convertAPI, name='convertAPI'),
]

cs2610/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.forms import ModelForm, Textarea

import datetime

class Blog(models.Model):
    title = models.CharField(max_length=200)
    author_name = models.CharField(max_length=50)
    content = models.TextField(max_length = 2000)
    posted_date = models.DateTimeField('date posted')
    def __str__(self):
        return self.content
    def was_published_recently(self):
        return self.posted_date >= timezone.now() - datetime.timedelta(days = 1)

class Comments(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    commenter_nickname = models.CharField(max_length=50)
    email = models.EmailField()
    content = models.TextField(max_length=1000)
    posted_date = models.DateTimeField('date commented')
    def __str__(self):
        return self.content
        


# Create your models here.

cs2610/gold/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

cs2610/goldapi/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Converter(models.Model):
    conversion = {
        'stone': 6350.2932, 
        'lbs': 453.59237, 
        't_oz': 31.103477, 
        'ton': 907184.74, 
        'kg': 1000
    }

cs2610/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Blog, Comments
from django.template import loader
from django.urls import reverse

import time
from django.utils import timezone


def tech(request):
    curTime = time.strftime("%c")
    template = loader.get_template('blog/tech.html')
    context = {
        'curTime': curTime,
    }
    return HttpResponse(template.render(context,request))

def aboot(request):
    curTime = time.strftime("%c")
    template = loader.get_template('blog/aboot.html')
    context = {
        'curTime': curTime,
    }
    return HttpResponse(template.render(context,request))

def archive(request):
    curTime = time.strftime("%c")
    blog_list = Blog.objects.order_by('-posted_date') 
    template = loader.get_template('blog/archive.html')
    context = {
        'blog_list': blog_list,
        'curTime': curTime,
    }
    return HttpResponse(template.render(context,request))

def index(request):
    curTime = time.strftime("%c")
    latest_blog_list = Blog.objects.order_by('-posted_date')[:3] 
    template = loader.get_template('blog/index.html')
    context = {
        'latest_blog_list': latest_blog_list,
        'curTime': curTime,
    }
    return HttpResponse(template.render(context,request))

def detail(request, blog_id):
    try:
        blog = Blog.objects.get(pk=blog_id)
    except Blog.DoesNotExist:
        raise Http404("Blog post does not exist")
    return render(request, 'blog/detail.html', {'blog': blog})

def comment(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    try:
        blog.comments_set.create(content=request.POST.get('commentbody', None),
                                 commenter_nickname=request.POST.get('nickname',None),
                                 email=request.POST.get('email',None),
                                 posted_date=timezone.now())
    except (KeyError, Comments.DoesNotExist):
        return render(request, 'blog/detail.html', {
            'blog': blog,
            'error_message': "You, uh, failed to comment",
        })
    else:
        blog.save()
    return HttpResponseRedirect(reverse('blog:detail',args=(blog.id,)))

# Create your views here.

cs2610/gold/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

def goldWeight(request):
    return render(request, 'gold/index.html', {})    

cs2610/goldapi/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse

from .models import Converter
import json

# Create your views here.

def convert(value, ufrom, uto):
    value = Converter.conversion[ufrom] * value
    value = value / Converter.conversion[uto]
    return value
        
def convertAPI(request):
    
    resp = {}
    
    if not request.GET.has_key('from') or not request.GET.has_key('to') or not request.GET.has_key('value'):
        resp['error'] = "Usage: to=[unit] from=[unit] value=[floating point number]"
    else:
        mto = request.GET['to']
        mfrom = request.GET['from']
        mvalue = float(request.GET['value'])
        result = convert(uto=mto,ufrom=mfrom,value=mvalue)
        resp = { "units":mto, "value":result }
        
    return HttpResponse(json.dumps(resp))
                

cs2610/blog/templates/blog/aboot.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>W E B &nbsp; D O G G O S - ABoot</title>
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
    </head>
    <body>
    <header>
        <h1> Doggoland Blog </h1>
        <img src="{% static 'blog/fibbonaci.jpg' %}" alt="f i b b o n a c i  b o y e" />
    </header>
    <nav>
      <ul>
        <li><a href="{% url 'blog:index' %}">Home</a></li>
        <li><a href="{% url 'blog:archive' %}">Archive</a></li>
        <li><span>Aboot doggos</span></li>
        <li><a href="{% url 'blog:tech' %}">Pupper Tech Tips</a></li>
      </ul>
    </nav>
    <main>
      <article>
      <h2> aboot doggos </h2>
        <img src="{% static 'blog/spookyboyes.jpg' %}" alt="s p o o k y   b o y e s" />
        <section>
          <h3> What is dug (doggo)? </h3>
          <p>
          The domestic dug (Canis lupus familiaris or Canis familiaris) is a uisually furry, carnivorous canid carnivoran mammal. The dug wis the first domesticatit ainimal an haes been widely kept as a wirkin, huntin, an pet companion. It is estimatit thare are atween 700 million an ane billion domestic dugs, makin them the maist abundant member o order Carnivora. <a href="https://sco.wikipedia.org/wiki/Dug">[1]</a>
          </p>
          <p>
 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu neque nisl. Nam in lacus quis orci scelerisque rutrum id non velit. Vivamus tristique magna eget leo bibendum pellentesque. Sed volutpat efficitur enim, eget molestie magna ultricies vitae. Cras ultrices efficitur placerat. Curabitur pulvinar elementum vulputate. Donec semper quis nulla eu posuere. Vivamus tincidunt libero sit amet lacus sagittis, eu tincidunt risus pharetra. Integer feugiat finibus leo, quis feugiat nulla scelerisque sed. Aliquam erat volutpat. Donec rutrum tortor quis enim porttitor ultrices. Fusce venenatis ante eget tellus fermentum sagittis. Vestibulum at condimentum lorem.  
          </p>
        </section>
      </article>
      <aside>
        <h2>picturs of dug</h2>
        <a href="{% static 'blog/ears.jpg' %}"><img src="{% static 'blog/ears.jpg' %}" alt="dug with sum gud ears"></a>
        <a href="{% static 'blog/puppers.jpg' %}"><img src="{% static 'blog/puppers.jpg' %}" alt="smol dugs"></a>
        <a href="{% static 'blog/aquapupper.jpg' %}"><img src="{% static 'blog/aquapupper.jpg' %}" alt="dug meets aquapupper"></a>
      </aside>
    </main>
    <footer>
    When you loaded this webpage, the time was: {{ curTime }}
    <br/>
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>. Jack Kiefer
    </footer>
   </body>
</html>

cs2610/blog/templates/blog/archive.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>W E B &nbsp; D O G G O S</title>
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
    </head>
    <body>
    <header>
        <h1> Doggoland Blog </h1>
        <img src="{% static 'blog/fibbonaci.jpg'%}" alt="f i b b o n a c i  b o y e" />
    </header>
    <nav>
      <ul>
        <li><a href="{% url 'blog:index' %}">Home</a></li>
        <li><span>Archive</span></li>
        <li><a href="{% url 'blog:aboot' %}">Aboot doggos</a></li>
        <li><a href="{% url 'blog:tech' %}">Pupper Tech Tips</a></li>
      </ul>
    </nav>
    <main>
      <article>
      {% if blog_list %}
        {% for blog in blog_list%}
        <section>
          <h3><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a></h3>
          <font color="gray">{{ blog.comments_set.count }} comments</font>
          <p>
          {{ blog.content | truncatewords:200 }}
          </p>
          <font color="gray">By {{ blog.author_name }}, published {{ blog.posted_date }}</font></br>
        </section>
        <hr>
        {% endfor %}
  
      {% else %}
      <p> No blogs! No mames!</p>
      {% endif %}
      </article>
    </main>
    <footer>
    When you loaded this webpage, the time was: {{ curTime }}
    <br/>
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>. Jack Kiefer
    </footer>
   </body>
</html>

cs2610/blog/templates/blog/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>W E B &nbsp; D O G G O S</title>
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
    </head>
    <body>
    <header>
        <h1> Doggoland Blog </h1>
        <img src="{% static 'blog/fibbonaci.jpg'%}" alt="f i b b o n a c i  b o y e" />
    </header>
    <nav>
      <ul>
        <li><a href="{% url 'blog:index' %}">Home</a></li>
        <li><a href="{% url 'blog:archive' %}">Archive</a></li>
        <li><a href="{% url 'blog:aboot' %}">Aboot doggos</a></li>
        <li><a href="{% url 'blog:tech' %}">Pupper Tech Tips</a></li>
      </ul>
    </nav>
    <main>
      <article>
          
<h2>{{ blog.title }}</h2>
<font color="gray">By {{ blog.author_name }}, published {{ blog.posted_date }}</font>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<p>{{ blog.content }}</p>
<hr>
<form action="{% url 'blog:comment' blog.id %}" method="post">
{% csrf_token %}
Name:</br>
<input type="text" name="nickname" /><br />
Email:</br>
<input type="email" name="email" /><br/>
Comment:</br>
<textarea name="commentbody" rows="10" cols="80"></textarea>
<br/>
<button type="submit">Submit</button>
</form>

{% for comment in blog.comments_set.all reversed %}
<hr>
<b>{{comment.commenter_nickname}}</b></br></br>
{{comment.content}}<br/></br>
<small>{{comment.posted_date}}</small></br></br></br>
{% endfor %}

      
      </article>
    </main>
    <footer>
    When you loaded this webpage, the time was: {{ curTime }}
    <br/>
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>. Jack Kiefer
    </footer>
   </body>
</html>

cs2610/blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>W E B &nbsp; D O G G O S</title>
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
    </head>
    <body>
    <header>
        <h1> Doggoland Blog </h1>
        <img src="{% static 'blog/fibbonaci.jpg'%}" alt="f i b b o n a c i  b o y e" />
    </header>
    <nav>
      <ul>
        <li><span>Home</span></li>
        <li><a href="aboot.html">Aboot doggos</a></li>
        <li><a href="tech.html">Pupper Tech Tips</a></li>
      </ul>
    </nav>
    <main>
      <article>
      {% if latest_blog_list %}
      <h2> Welcome frens </h2>
        {% for blog in latest_blog_list %}
        <section>
          <h3><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a></h3>
          <p>
          {{ blog.content | truncatewords:200 }}
          </p>
        </section>
        {% endfor %}
      
      {% else %}
      <p> No blogs! No mames!</p>
      {% endif %}
      
      </article>
      <aside>
        <h2>Featured Good Boys</h2>
        <a href="{% static 'blog/hipster.jpg' %}"><img src="{% static 'blog/hipster.jpg' %}" alt="Distinguished scarf doggo"></a>
        <a href="{% static 'blog/smolfren.jpg' %}"><img src="{% static 'blog/smolfren.jpg' %}" alt="Doggo with smol fren"></a>
      </aside>
    </main>
    <footer>
    When you loaded this webpage, the time was: {{ curTime }}
    <br/>
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>. Jack Kiefer
    </footer>
   </body>
</html>

cs2610/blog/templates/blog/tech.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>W E B &nbsp; D O G G O S - Pupper Tech Tips</title>
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
    </head>
    <body>
    <header>
        <h1> Doggoland Blog </h1>
        <img src="{% static 'blog/fibbonaci.jpg'%}" alt="f i b b o n a c i  b o y e" />
    </header>
    <nav>
      <ul>
        <li><a href="{% url 'blog:index' %}">Home</a></li>
        <li><a href="{% url 'blog:archive' %}">Archive</a></li>
        <li><a href="{% url 'blog:aboot' %}">Aboot doggos</a></li>
        <li><span>Pupper Tech Tips</span></li>
      </ul>
    </nav>
    <main>
      <article class="flex-container">
      <h2> pupper tech tips </h2>
        

          <div class="lolwut">
          <table>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Example</th>
            </tr>
            <tr>
                <td>git init</td>
                <td>Initializes a new repository</td>
                <td><code>git init</code></td>
            </tr>
            <tr>
                <td>git add <em>filename</em></td>
                <td>Stages changes within file(s) to the repository</td>
                <td><code>git add .</code></td>
            </tr>
            <tr>
                <td>git reset</td>
                <td>You screwed up. pls go back</td>
                <td><code>git reset --hard</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
                     <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
          </table>
          </div>
       

          <div class="rekt">
          <table>
            <tr>
                <th>Bleh</th>
                <th>Dlorg</th>
                <th>Exismf</th>
            </tr>
            <tr>
                <td>no</td>
                <td>blehsrroooo</td>
                <td><code>yessssssss</code></td>
            </tr>
            <tr>
                <td>git add <em>filename</em></td>
                <td>Sorry</td>
                <td><code>git addplfj .</code></td>
            </tr>
            <tr>
                <td>git reset</td>
                <td>You screwed up. pls go back</td>
                <td><code>git reset --hard</code></td>
            </tr>
                 <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
          </table>
          </div>


          <div class="twelve">
          <table>
            <tr>
                <th>Borg</th>
                <th>DesPicard</th>
                <th>Wesley Crusher</th>
            </tr>
            <tr>
                <td>INCREASE POWER TO MAIN PHASER ARRAY</td>
                <td>PLASMA CORE EJECTION IMMINENT</td>
                <td><code>PLASMA CORE EJECTION IMMINENT</code></td>
            </tr>
               <tr>
                <td>worf add <em>filename</em></td>
                <td>yes</td>
                <td><code>dead weight</code></td>
            </tr>
            <tr>
                <td>worf add <em>filename</em></td>
                <td>yes</td>
                <td><code>dead weight</code></td>
            </tr>
            <tr>
                <td>worf add <em>filename</em></td>
                <td>yes</td>
                <td><code>dead weight</code></td>
            </tr>
            <tr>
                <td>worf add <em>filename</em></td>
                <td>yes</td>
                <td><code>dead weight</code></td>
            </tr>
            <tr>
                <td>game night</td>
                <td>game night</td>
                <td><code>what game</code></td>
            </tr>
            <tr>
                <td>git rekt</td>
                <td>Hit the gym</td>
                <td><code>Bruh, let's go git rekt at the iron temple</code></td>
            </tr>
          </table>
          </div>
       

     </article>
    </main>
    <footer>
    When you loaded this webpage, the time was: {{ curTime }}
    <br/>
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>. Jack Kiefer
    </footer>
   </body>
</html>

cs2610/gold/templates/gold/index.html
<html>
    <head>
        <meta charset="utf-8">
        <title>YOU ARE WORTH YOUR WEIGHT IN GOLD</title>
    </head>
    <body>
        <div>
            <h2>Calculate your the worth weight in gold!</h2>
            You are worth your weight in gold! Calculate the precise worth of your weight in gold and see that it doesn't even amount to how much you're truly worth.
            </br>Enter your weight in lbs:<br />
            <input type="number" id="weight" name="weight">
            <button type="button" onclick="calculate()">Calculate</button>
            <p id="result"></p>
        </div>
        <script type="text/javascript">
            var calculate = function() {
                var weightLbs = document.querySelector("#weight").value;
                var unitconvURL = 'https://cs2610-jackkiefer.c9users.io/convertAPI/?from=lbs&to=t_oz&value=' + weightLbs;
                var unitconvReq = new XMLHttpRequest();
                unitconvReq.open('GET', unitconvURL);
                unitconvReq.responseType = 'json';
                unitconvReq.send();
                
                var ozWeight;
                unitconvReq.onload = function() {
                    var json = unitconvReq.response;
                    console.log(json);
                    ozWeight = json['value']
                }
                
                var goldRUrl = 'https://www.quandl.com/api/v3/datasets/LBMA/GOLD.json?api_key=qqcRs76CozC2yYc-xutC&column_index=2&start_date=2017-10-01&end_date=2017-10-10';
                var goldR = new XMLHttpRequest();
                goldR.open('GET', goldRUrl);
                goldR.responseType = 'json';
                goldR.send();
                goldR.onload = function() {
                    var json = goldR.response;
                    console.log(json);
                    document.querySelector('#result').textContent = "Your weight in gold is worth: $" + json['dataset']['data'][0][1] * ozWeight;
                }
            }   
            
        </script>
    </body>
</html>